# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '**/*.csproj'
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration Release'
- task: DotNetCoreCLI@2
  displayName: Run Unit Tests
  inputs:
    command: test
    projects: '**/*Test*/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
- task: AzureRmWebAppDeployment@4
  displayName: Deploy to Azure
  inputs:
    ConnectedServiceName: 'Visual Studio Enterprise – MPN(e0313a52-5c21-42d6-b971-7b0ba3a74b46)'
    WebAppKind: 'apiApp'
    WebAppName: 'CivEngage-API'
    DeployToSlotOrASEFlag: true
    ResourceGroupName: 'civ-engage'
    SlotName: 'Dev'
